### ISSUE TITLE
Celo All-Core Dev Call 6

### ISSUE THREAD

**Issue by YazzyYaz** [celo-org/celo-proposals#172]
# Celo All-Core Devs Call 6
![All-Core-Dev-Call-end-card](https://user-images.githubusercontent.com/9094204/109044800-d5dff000-76a0-11eb-9f1f-b1992358e0bc.jpg)

## Event Details 
When: Thursday, March 11, 2021, 1 PM EST/10 AM PST, 60 minutes max
Where: Celo Zoom [Event](https://zoom.us/j/98175463252) 
Meeting ID: 981 7546 3252
Passcode: 290324
Calendar Event: Add to your calendar [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFwaTlhamQ2dmJtbjg1cHRhdjNkaW0zY3UgY185c3U2aWNoMXVobWV0cjRvYjNzaWo2a2Fxc0Bn&tmsrc=c_9su6ich1uhmetr4ob3sij6kaqs%40group.calendar.google.com)

Focus: Node Attestation Incentives, Donut Schedule

## Agenda
* [CIP 32](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0032.md)
* [Update to Implementing CIP-33: Multi Currency Support](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0033.md)
    * [CGP-23: cEUR Oracle Activation](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0023.md)
    * [CGP-25: Set Constitutional Parameters for New Contracts and Methods Added By CR3](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0025.md)
    * [CGP-24: cEUR Activation](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0024.md)
* [Update to Implementing CIP-29: Making Celo more graceful ](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0029.md)    
    * [CGP-27: Set gracePeriod Value](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0027.md)
* [CIP 37: Unambiguous name for ERC-20 on Celo chain](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0037.md)    

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by YazzyYaz** [comment]
Video for the call: https://youtu.be/lz3O40WpZ2c

**Comment by willkraft** [comment]
Here are some notes summarizing the call: [Celo All-Core Developers Call_2021.03.11.pdf](https://github.com/celo-org/celo-proposals/files/6127560/Celo.All-Core.Developers.Call_2021.03.11.pdf)

**Comment by YazzyYaz** [comment]
@willkraft thank you so much for your valuable notes!

**Comment by willkraft** [comment]
You're welcome!
