### ISSUE TITLE
Celo Governance Call 6: Governance Working Group

### ISSUE THREAD

**Issue by YazzyYaz** [celo-org/celo-proposals#201]
# Celo Governance Call 6: Governance Working Group

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: April 8th, 2021. 1 PM EST / 10 AM PST 60 minutes max
Where: Celo Zoom [Event](https://zoom.us/j/92038872988) (Instructions on joining found in the calendar event below)
Zoom Passcode: 194989
Calendar Event: Add to your calendar [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=MGUyYTB2ZW1mdDVhc3IwNGsxcHBodXN2bmwgY185c3U2aWNoMXVobWV0cjRvYjNzaWo2a2Fxc0Bn&tmsrc=c_9su6ich1uhmetr4ob3sij6kaqs%40group.calendar.google.com)
Documentation: [Celo Governance Call Working Group ](https://docs.google.com/document/d/1ZuYdwh4ZFtiEvXaE7Ow6NhKjBvLwjn-M_-ryDBuPZLM/edit#heading=h.wun1qns5uzxr)

**Note: This is a special governance call for creating a working group around improving the governance process.**

### Tensions
* Governance and CGP process not as specified as CIP Process. See Cosmo's [example](https://github.com/cosmos/governance).
* Need to resolve inconsistency between proposalID and CGP Numbers.
* CGPs with missing sections or underspecified.
* Need more CGP editors.
* CGP governable parameters need to be tracked down in the CIP process.
* Coordination with approvers needs a more specified Verification process.
    * Provide timely push notifications to approvers (when proposals are posted and as expiry approaches), to give them time to review 
* `celocli governance:view` is difficult to understand and fails to helpfully parse some proposals.
* Document the proposal code verification procedure. Make sure many non-cLabbers know of it and have successfully invoked it. (Sufficiently many to really catch problems, if they arise.)
* Never post proposals until they are fully specified, including code verification procedures.
* Try to make CGP text reasonably stand-alone, giving the gist even to readers who don't follow the links. (But do provide the links for further context and community discussion.)
* Proactively seek community input on proposals before they're posted. In particular, seek non-cLabs input on proposals that involve privileges to cLabs or cLabbers.
* Ensure Audit Reports are publicized prior to submission.
* Move governance to its own repository outside the current repo to separate CIP and CGP processes.

### Ideas
* Ideas by @aslawson this [doc](https://docs.google.com/document/d/1_aLO9xnO6ho02BuFGTReuNsDWMEhDS4Omsc48CiN4O8/edit)

### Action Items
* 

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by nambrot** [comment]
Would love to chat about https://github.com/celo-org/celo-monorepo/issues/5051

**Comment by willkraft** [comment]
Hey all, here are key takeaways from today's governance call: [Celo Governance Call #6_2021.04.08.pdf](https://github.com/celo-org/celo-proposals/files/6282634/Celo.Governance.Call.6_2021.04.08.pdf)

**Comment by YazzyYaz** [comment]
Thanks Will!

Video of the call: https://youtu.be/SuefN6rlD2A

**Comment by luisfranco123** [comment]
Hello, good morning, could you exchange jealousy for dollars in the app, value?

**Comment by luisfranco123** [comment]
Hello, good morning, could you change the cryptocurrency zeal for dollars or another cryptocurrency in the app, value?
