### ISSUE TITLE
Celo All-Core Dev 7

### ISSUE THREAD

**Issue by YazzyYaz** [celo-org/celo-proposals#207]
# Celo All-Core Devs Call 7
![All-Core-Dev-Call-end-card](https://user-images.githubusercontent.com/9094204/109044800-d5dff000-76a0-11eb-9f1f-b1992358e0bc.jpg)

## Event Details 
When: Thursday, April 15th, 2021, 1 PM EST/10 AM PST, 60 minutes max
Where: Celo Zoom [Event](https://zoom.us/j/97408484932) 
Meeting ID: 974 0848 4932
Passcode: 474576
Calendar Event: Add to your calendar [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=NHJxbmdqbjI0M2VoM2toMjlndm44MzA4bmMgY185c3U2aWNoMXVobWV0cjRvYjNzaWo2a2Fxc0Bn&tmsrc=c_9su6ich1uhmetr4ob3sij6kaqs%40group.calendar.google.com)

## Summary

The Celo All-Core Dev Call is the "All Hands" call for all Celo Core Developers to coordinate technical specifications and proposals and discussions to the Celo Platform.

## Agenda

* Baklava Donut Hardfork Retro, Expectations for Mainnet
* [CIP-10](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0010.md)

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by mikereinhart** [comment]
Looking forward to attending! Can we discuss [CIP-10](https://github.com/celo-org/celo-proposals/pull/17)? I think this is a great way to make it easier for stakeholders to securely participate in Celo.

**Comment by AlexBHarley** [comment]
@mikereinhart feel free to make your thoughts known on https://github.com/celo-org/celo-proposals/issues/76 before the call.

**Comment by YazzyYaz** [comment]
ACD 7 Video Call: https://youtu.be/o2qydfm0pxg
