### ISSUE TITLE
Celo Wallet and (d)App Council #6

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-proposals#307]
### Housekeeping:

- [x] Send calendar invite for January
- [ ] Add agenda items to vote on (before publicising)
- [x] Publicise on forums (Discord, Twitter, Forum) and Celo newsletter (Yaz)

### References

Links to previous meeting:
- Notion page: [Celo Wallet Council Meeting Notes](https://www.notion.so/celoplatform/Celo-Wallet-Council-61dfe28e98a543409cf6c181b132c4de)
- Github ticket (with agenda): [Celo Wallet Council Call 5 #295](https://github.com/celo-org/celo-proposals/issues/295)

**Comment by arthurgousset** [comment]
Closed in favour of this ticket ([Celo Wallet and (d)App Council #6 #9120](https://github.com/celo-org/celo-monorepo/issues/9120)) in celo-monorepo.

**Comment by arthurgousset** [comment]
Proposed agenda items 👇  Feel free to add your ideas (however small or big) and upvote/downvote

**Comment by arthurgousset** [comment]
@nityas - Wallet Connect v1/v2 support

**Comment by yasharpm** [comment]
Users can do KYC once (on any wallet) and become whitelisted everywhere even outside Celo. I can explain how.

**Comment by yasharpm** [comment]
Introduction of binary wallets that work both based on private keys or verified phone numbers. This will be a huge breakthrough for blockchains: You no longer need to worry about loosing your keys.

**Comment by arthurgousset** [comment]
Closing this ticket because the meeting took place as expected ✅
