### ISSUE TITLE
Celo Wallet and (d)App Council #7 [February]

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-proposals#308]
### Join
Google Meet: [meet.google.com/uwj-wfse-uzm](https://meet.google.com/uwj-wfse-uzm)
Recording: [Google Drive](https://drive.google.com/file/d/1TShcoaeg1FPtoP0DrzYMAEBWJmPE8vx-/view?usp=sharing)

### Useful links

- Notion page with meeting notes: [Celo Wallet Council Meeting Notes](https://www.notion.so/celoplatform/Celo-Wallet-Council-61dfe28e98a543409cf6c181b132c4de)
- Last meeting: [Celo Wallet and (d)App Council #6](https://github.com/celo-org/celo-proposals/issues/307)
- Forum post: [Celo Wallet and (d)App Council #7 [February]](https://forum.celo.org/t/celo-wallet-and-d-app-council-7-february/2769) 👇 

-------------Copied from forum----------------

Hey all :wave:

The monthly Celo Wallet and (d)App Council meeting #7 is taking place on **Wednesday, January 5th (9am PDT/6pm CEST)**.

### :calendar: What is this?

- A *monthly* meeting for Celo **developers, founders,** **product** people (anyone really!) to share
  - wishes,
  - pain points, and
  - ideas

### 🗒️  Agenda

- Check out, vote, and add to the agenda on Github: [Celo Wallet and (d)App Council #7 [February]](https://github.com/celo-org/celo-proposals/issues/308)
- 🗳️ You can **upvote/downvote** agenda items using the `+1` (👍 ) and `-1` (👎 ) emojis.
- ✍️ Please feel free to add agenda items (however small or big!) on Github. For example:

  - broad discussion topics to **amplify** your ideas/features/frictions,
  - requests for **feedback** (from the community),
  - roadmap **updates** ,
  - etc (anything that would be useful for you really!)

### :star_struck: How do I participate?

- Join using Google Meet: meet.google.com/uwj-wfse-uzm
- Take a peek at the [previous meeting notes](https://www.notion.so/celoplatform/Celo-Wallet-and-d-App-Council-monthly-61dfe28e98a543409cf6c181b132c4de)

See you there! :rocket:
--------------------------------------------

**Comment by arthurgousset** [comment]
### Housekeeping:

- [ ] Send update calendar invite with Github link
- [ ] Add agenda items to vote on
- [ ] Publicise on forums (Discord, Twitter, Forum) and Celo newsletter (Yaz)

**Comment by arthurgousset** [comment]
### Proposed agenda items 👇  

Please feel free to add agenda items (however small or big!) below.
 
For example:
- broad discussion topics to **amplify** your ideas/features/frictions, 
- requests for **feedback** (from the community), 
- roadmap **updates**,
- etc (anything that would be useful for you really!) 

🗳️ You can upvote/downvote agenda items using the `+1` (👍 ) and `-1` (👎 ) emojis.

**Comment by arthurgousset** [comment]
Roadmap update: [Kaala.app](https://kaala.app/)

Context: 
- Kaala is a non-custodial wallet in the Celo ecosystem
- Benoit will be sharing an update on what they are currently working on

**Comment by arthurgousset** [comment]
Roadmap update: [Nom.space](https://nom.space/)

Context:

- Nomspace is an ENS fork on Celo
- Their namespace has seen strong growth with ~50k names reserved/~40k unique wallets

**Comment by napolean0** [comment]
We would love to present our project and onboard Celo Dapps
**Project**: https://dapplooker.com/#features
**Celo Support Details**: https://forum.celo.org/t/celo-dapps-analytics-visualization-platform/2607/3

**Comment by jeanregisser** [comment]
Spread the word about [Valora's Dapp Bakeoff Contest](https://valoraapp.com/bakeoff) and answer questions dapps developer may have about it.

**Comment by cajubelt** [comment]
We'd like to introduce FiatConnect, a standardized API for cash-in/cash-out providers that will enable config-driven integrations with wallets

**Comment by arthurgousset** [comment]
Adding the recording for future reference: [Google Drive](https://drive.google.com/file/d/1TShcoaeg1FPtoP0DrzYMAEBWJmPE8vx-/view?usp=sharing)

**Comment by arthurgousset** [comment]
Closing this because the call successfully took place. The next one is scheduled here #311

**Comment by 0xarthurxyz** [comment]
Thanks to all who attended the recent Wallet and (d)App Council meeting. Here is the

- Meeting recording :movie_camera:: [https://drive.google.com/file/d/14wGDVcOK3wK3frMfX-xR8-TkkOP23LBg/view](https://drive.google.com/file/d/1TShcoaeg1FPtoP0DrzYMAEBWJmPE8vx-/view)
- Meeting notes :memo:: [https://www.notion.so/celoplatform/Celo-Wallet-Council-61dfe28e98a543409cf6c181b132c4de 2](https://www.notion.so/Celo-Wallet-and-d-App-Council-monthly-61dfe28e98a543409cf6c181b132c4de)

**Comment by napolean0** [comment]
Thanks @0xarthurxyz for sharing 👍
