### ISSUE TITLE
Celo Wallet and (d)App Council #8 [March]

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-proposals#311]
### Join
Google Meet: [meet.google.com/uwj-wfse-uzm](https://meet.google.com/uwj-wfse-uzm)
Recording: tbd

### Useful links

- Notion page with meeting notes: [Celo Wallet Council Meeting Notes](https://www.notion.so/celoplatform/Celo-Wallet-Council-61dfe28e98a543409cf6c181b132c4de)
- Last meeting: [Celo Wallet and (d)App Council #7 [February]](https://github.com/celo-org/celo-proposals/issues/308)
- Forum post: tbd 

Hey all :wave:

The monthly Celo Wallet and (d)App Council meeting is taking place on **Wednesday, March 2nd (9am PDT/6pm CEST)**.

### :calendar: What is this?

- A *monthly* meeting for Celo **developers, founders,** **product** people (anyone really!) to share
  - wishes,
  - pain points, and
  - ideas

### 🗒️  Agenda

- Check out, vote, and add to the agenda below
- 🗳️ You can **upvote/downvote** agenda items using the `+1` (👍 ) and `-1` (👎 ) emojis.
- ✍️ Please feel free to add agenda items (however small or big!) on Github. For example:

  - broad discussion topics to **amplify** your ideas/features/frictions,
  - requests for **feedback** (from the community),
  - roadmap **updates** ,
  - etc (anything that would be useful for you really!)

### :star_struck: How do I participate?

- Join using Google Meet: meet.google.com/uwj-wfse-uzm
- Take a peek at the [previous meeting notes](https://www.notion.so/celoplatform/Celo-Wallet-and-d-App-Council-monthly-61dfe28e98a543409cf6c181b132c4de)

See you there! :rocket:
--------------------------------------------

**Comment by arthurgousset** [comment]
### Housekeeping:

- [x] Send update calendar invite with Github link
- [x] Add agenda items to vote on
- [x] Publicise on forum and Discord

**Comment by arthurgousset** [comment]
### Proposed agenda items 👇  

Please feel free to add agenda items (however small or big!) below.
 
For example:
- broad discussion topics to **amplify** your ideas/features/frictions, 
- requests for **feedback** (from the community), 
- roadmap **updates**,
- etc (anything that would be useful for you really!) 

🗳️ You can upvote/downvote agenda items using the `+1` (👍 ) and `-1` (👎 ) emojis.

**Comment by 0xarthurxyz** [comment]
Closing this in favour of to the discussion item [here](https://github.com/celo-org/celo-monorepo/discussions/9304).
