### ISSUE TITLE
invalid discord link in ip-0000.md file

### ISSUE THREAD

**Issue by mrodclabs** [celo-org/celo-proposals#372]
Hello,

Found another invalid discord link within the ip-0000.md file.

Please fix it or remove it.

Thank you

**Comment by mrodclabs** [comment]
Hello,

any update about this issue?

**Comment by karlb** [comment]
Fixed in https://github.com/celo-org/celo-proposals/commit/10dd6191ff5521da01e750a4e923e6e2138dc232. That already happened on May 8, 2023. We were just slow in closing this issue.
