### ISSUE TITLE
Celo Governance Call #2

### ISSUE THREAD

**Issue by YazzyYaz** [celo-org/celo-proposals#92]
# Celo Governance Call 2

When: December 3rd, 2020. 12 PM EST / 9 AM PST 60 minutes max
Where: Celo Zoom Event (Instructions on joining found in the calendar event below)
Calendar Event: Add to your calendar [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=N2RsY3JjYWNoajJwZjRiYTBxdjVnYWJjdW0gY185c3U2aWNoMXVobWV0cjRvYjNzaWo2a2Fxc0Bn&tmsrc=c_9su6ich1uhmetr4ob3sij6kaqs%40group.calendar.google.com)
Focus: Discussing Governance Proposals and understanding the motivation behind them with the community

## Agenda
* [CGP-17](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0017.md)
* [CGP-15](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0015.md)
* [CGP-14](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0014.md)
* [CGP-16](https://github.com/celo-org/celo-proposals/blob/master/CGPs/0016.md)

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by devme25** [comment]
Hi we (Deepak, MultiSig; Patrick, Validator Capital/Moola; Dee, Usopp.Club) would like to propose CGP 0017 (PR made, yet to be committed) to active the Celo Community Fund.
Requesting: 30min
10-15 min - Proposal Presentation
15-20min - Feedback and Q&A

**Comment by cla-bel** [comment]
If there's time at the end would it be possible to have 5 min to share a quick update/heads up that cLabs is kicking off work on additional stable assets and expect to share more info for discussion shortly.

**Comment by YazzyYaz** [comment]
Video for the call: https://youtu.be/BUXFL86P63U
