### ISSUE TITLE
Celo All-Core Devs Call 3: Last Call for Donut

### ISSUE THREAD

**Issue by YazzyYaz** [celo-org/celo-proposals#96]
# Celo All-Core Devs Call 3: Last Call for Donut
When: Friday, December 11th, 2020, 1 PM EST/10 AM PST, 60 minutes max
Where: Celo Zoom [Event](https://zoom.us/j/95670412573) (Instructions on joining found in the calendar event below)
Calendar Event: Add to your calendar [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=MW40bWliZHBrcXNxZ2JtNWppOTd1ZmxhdGggY185c3U2aWNoMXVobWV0cjRvYjNzaWo2a2Fxc0Bn&tmsrc=c_9su6ich1uhmetr4ob3sij6kaqs%40group.calendar.google.com)
Focus: Finalizing Donut Meta Specification

## Agenda
* [CIP 29](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0029.md) Make Celo More Graceful 
* [CIP 27](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0027.md) Donut Meta CIP Discussions And Last Call

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by prestwich** [comment]
We have this scheduled to be Last Call for Donut. @YazzyYaz we should probably put that in the title

**Comment by YazzyYaz** [comment]
@prestwich Title has been Updated

**Comment by YazzyYaz** [comment]
Video of the call: https://youtu.be/DBFBRIbLqeM
